baseurl = "http://syzygy-intro1.surge.sh/"
languageCode = "en-us"
title = "Introduction to Syzygy"
theme = "hugo-material-docs"
tags = ["syzygy", "jupyterhub", "material", "documentation"]
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Michael Lamoureux"
	description = "An introduction syzygy.ca service."
	copyright = "Michael Lamoureux"
    email = "jupyter@pims.math.ca"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/pimsmath/syzygy-intro"

	version = "0.0.9"
	logo = ""
	favicon = "/img/logos/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = ['static/application.css']
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "indigo"
    	accent  = "orange"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "pimsmath"
	github  = "pimsmath"
	email   = "jupyter@pims.math.ca"

[[menu.main]]
	name   = "Front"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "Getting Started"
	url    = "getting-started/"
	weight = 20


[[menu.main]]
	name   = "The Basic Elements"
	url    = "the-basic-elements/"
	weight = 30


[[menu.main]]
	name   = "Python for Computing"
	url    = "python-for-computing/"
	weight = 40


[[menu.main]]
	name   = "Julia for Computing"
	url    = "julia-for-computing/"
	weight = 50


[[menu.main]]
	name   = "R for Computing"
	url    = "r-for-computing/"
	weight = 60


[[menu.main]]
	name   = "Unix Tricks"
	url    = "unix-tricks/"
	weight = 70


[[menu.main]]
	name   = "Using Git and GitHub"
	url    = "using-git-and-github/"
	weight = 80

[[menu.main]]
	name   = "Troubleshooting/FAQ"
	url    = "troubleshooting/"
	weight = 90

[[menu.main]]
	name   = "Acknowledgements"
	url    = "acknowledgements/"
	weight = 100


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
